version: '3'

services:
  teamspeak:
    image: teamspeak
    container_name: ${TS3_CONTAINER_NAME}  # Имя контейнера для TeamSpeak из .env
    restart: always
    ports:
      - "${TS3_PORT_UDP}:9987/udp"  # Порт для голосового соединения TeamSpeak из .env
      - "${TS3_PORT_QUERY}:10011"   # Порт для ServerQuery (Telnet) из .env
      - "${TS3_PORT_FILE}:30033"    # Порт для передачи файлов из .env
    volumes:
      - ./teamspeak-data:/var/ts3server
    environment:
      TS3SERVER_LICENSE: ${TS3SERVER_LICENSE}  # Принятие лицензионного соглашения

  ts3manager:
    image: "joni1802/ts3-manager"
    container_name: ${TS3MANAGER_CONTAINER_NAME}  # Имя контейнера для TeamSpeak из .env
    ports:
      - "${TS3MANAGER_PORT}:8080"
    environment:
      - WHITELIST=${TS3MANAGER_WHITELIST}